package wacc

class Compiler {
    
    import java.nio.file.{Files, Paths}
    import scala.io.Source

    private var filename = ""
    private var fileData = ""

    // default values for flags
    private var parse = false
    private var typecheck = false
    private var full_compile = true
    private var targetArch = "arm32"
    private var optimise = false
    private var assembly = false
    private var execute = false
    private var directory = "."

    def readTarget(): Boolean = {

        val path = Paths.get(filename)
        if (!Files.exists(path)) {
            sys.error("File '" + filename + "' not found")
            return false
        }

        val builder = new StringBuilder()
        for (line <- Source.fromFile(filename).getLines()) {
            builder.append(line)
            builder.append("\n")
        }
        fileData = builder.toString()
        return true
    }

    def compile: Int = {
        // println("*--- Compiling '" + filename + "' ---*")
        // println(fileData)
        return 0
    }



}

object Compiler {

    def apply(targetFile: String): Compiler = {
        var c = new Compiler
        c.filename = targetFile
        c
    }

    def printUsage = {
        println("Usage: ./compile [options] <target.wacc>")
        println("   options:")
        println("       -p, --only-parse        Parse only. Check the input file for syntax errors and generate an AST.")
        println("       -s, --only-typecheck    Semantic check. Parse the file for syntax and semantic errors and generate an AST.")
        println("       -c, --full-compile      Full Compilation (default). Run the full compilation process.")
        println("       -t, --target            Target. Select target architecture (default arm32, options: x86-64-intel or x86-64).")
        println("       -o, --optimise          Optimise. Run ARM Peephole optimisations over the generated assembly code.")
        println("       -a, --print-assembly    View Assembly. Display ARM assembly code generated by the code generator.")
        println("       -x, --execute           Execute. Assemble and Emulate the generated ARM code and display its output.")
        println("       -d, --directory         Give directory of wacc files.")
        println("       -h, --help              Show this message.")
        println()
        println("   target.wacc: path to wacc program file to compile (or target directory if --directory option set)")
    }
}